name: Trigger auto deployment for container-app-xdektxwo65zz4

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-xdektxwo65zz4-AutoDeployTrigger-3715c9af-50bd-43a3-8678-f7d6a28e81f1.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPXDEKTXWO65ZZ4_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPXDEKTXWO65ZZ4_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPXDEKTXWO65ZZ4_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPXDEKTXWO65ZZ4_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPXDEKTXWO65ZZ4_REGISTRY_PASSWORD }}
          containerAppName: container-app-xdektxwo65zz4
          resourceGroup: ragappfastapiqdrantreactb530
          imageToBuild: default/container-app-xdektxwo65zz4:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


